<a href="https://colab.research.google.com/github/Pragadesh-45/Nivu-5-Day-Bootcamp-Notebooks/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Installation

In [8]:
!pip install numpy

In [9]:
# importing numpy
import numpy as np

#Single Dimension Numpy Array


In [10]:
a = np.array([1,2,3,4,5])

print(a)
print(type(a))
print(a[1])
print(a[-1])
print(a[1:])

a[2] = 10
print(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
2
5
[2 3 4 5]
[ 1  2 10  4  5]


#Multi Dimension Numpy Array

In [17]:
a_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(a_mul[0])
print(a_mul[0][1])

[1 2 3]
2


In [20]:
# Shape of array
print(a_mul.shape)

(3, 3)


In [21]:
# depth/levels of array
print(a_mul.ndim)

2


In [22]:
# Size of the array
print(a_mul.size)

9


In [23]:
# Data type
print(a_mul.dtype)

int64


In [ ]:
a_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [24]:
a = np.full((2,3,4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [26]:
a = np.ones((2,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [30]:
print(np.empty((2,2,2)))

[[[5.03333131e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [35]:
x_values = np.arange(0,1000,5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [39]:
# for even distribution
np.linspace(0,1000,5)

array([   0.,  250.,  500.,  750., 1000.])

# Math Operations


In [42]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [45]:
a = np.array([[1,2,3],
              [5,4,3]])

# numpy math functions - sqrt, sin, cos, tan, log, arctan, exp
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.23606798 2.         1.73205081]]


#Array Methods

In [49]:
a = np.array([1,2,3])

np.append(a,a)            # array([1, 2, 3, 1, 2, 3])

np.insert(a, 3, [4,5,6])  # array([1, 2, 3, 4, 5, 6])

np.delete(a, 1)           # array([1, 3])

array([1, 3])

# Structuring Methods

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [54]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(a.transpose())
print()
print(a.T)
print()
print(a.swapaxes(0,1))

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


# Concatenation, Stacking, Splitting

In [ ]:
a1 = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

a2 = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(np.concatenate((a1, a2), axis=0))

print(np.concatenate((a1, a2), axis=1))

print(np.stack((a1, a2)))

In [63]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


Aggreate functions (min, max, mean, std, sum, median)

In [64]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())

print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


#Random

In [65]:
number = np.random.randint(100)
print(number)

27


In [68]:
numbers = np.random.randint(2, size=(2,3,4))

print(numbers)

[[[0 0 0 0]
  [0 1 1 1]
  [0 1 1 0]]

 [[0 0 1 1]
  [1 0 1 1]
  [1 0 0 0]]]


In [70]:
numbers = np.random.choice([10,20,30,40,50], size=(2,3,4))

print(numbers)

[[[40 20 40 10]
  [10 10 30 40]
  [50 50 20 10]]

 [[10 50 30 40]
  [10 30 40 10]
  [20 10 50 30]]]


# Importing & Exporting

In [71]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])


np.save("myarray.npy", a)

In [72]:
np.load("myarray.npy")

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])